### ISSUE TITLE
ScrollView in the web app

### ISSUE THREAD

**Issue by imaximumGit** [dedis/student20_pop#17]
The text go outside the bound of the Scrollview (it have to stay in the black rectangle and add a scroll bar to be able to see all the text) in the ConnectConfirm component on the web version

**Comment by RaulinN** [comment]
Cannot reproduce this bug since clicking on the blue camera icon in `connect` makes the navigation bar "selected tab" line indicator stuck between two tabs (`home` and `connect`). Clicking again on the blue camera icon does nothing more

<img width="1402" alt="Screenshot 2020-10-17 at 17 27 48" src="https://user-images.githubusercontent.com/44499915/96346843-3ed5ac80-109e-11eb-8165-6e140d72adfc.png">

iOS version behaves normally

**Comment by imaximumGit** [comment]
Explain more in the top comment, the bug appear only in the web app, the IOS and android work

**Comment by RaulinN** [comment]
Solved both issues! See commit above
